### ISSUE TITLE
Error: Unable to parse series name from filename

### ISSUE THREAD

**Issue by urbster1** [jamerst/AutoTag#4]
Hi! I am running this in a folder structure with files as follows:
`Series/Season 1/S01E01 Title.mp4`

using `autotag -t --no-rename -v .`

Running with `--manual "Series"` doesn't make a difference, and it's not clearly documented how that feature should be used. Either way, it finds all episodes, then outputs the above error. Any help is appreciated - thanks!

**Comment by jamerst** [comment]
Hi,

AutoTag is designed to parse all the required information from just the filename, not the file path, so it's not able to find the series name in your file structure.

The `--manual` flag doesn't take any options, it simply allows the correct series to be chosen from the results returned from searching. It's useful when there are multiple series in the results with very similar names.

I'll look into adding an option to manually specify the file/directory structure to parse the episode info, or failing that an option to manually specify the series name to be searched for.

**Comment by jamerst** [comment]
This should now be addressed in v3.0.2.

If you run AutoTag with `--pattern ".*/(?<SeriesName>.+)/Season (?<Season>\d+)/S\d+E(?<Episode>\d+)"` that _should_ be able to parse episodes in your file structure.

**Comment by urbster1** [comment]
That's great! Thanks for your help!

**Comment by urbster1** [comment]
Hmm, I'm still unable to get `-p` to work. I've tried escaping the pattern with single- and double-quotes but either way I'm getting the following error when running `autotag -t -v --no-cover -p '.*/(?<SeriesName>.+)/Season (?<Season>\d+)/S\d+E(?<Episode>\d+).*' .`
```
./S01E01 Title.mp4
    Error: Input string was not in a correct format
````

**Comment by jamerst** [comment]
Looks like there was a bug when used with relative paths, I've uploaded v3.0.3, that should hopefully work this time.

**Comment by urbster1** [comment]
Thanks - also this is slightly unrelated, but if an episode contains a "?"
in the title, renaming fails. Maybe some invalid characters should be
omitted or replaced?

**Comment by jamerst** [comment]
That's odd, any invalid characters should definitely be removed, maybe `Path.GetInvalidFileNameChars()` doesn't return _all_ invalid characters?

I assume this is on Windows? I'm Linux-based so I don't have any issues with question marks in file names.

If you wouldn't mind creating a separate issue, I'll investigate it further when I get chance.

**Comment by urbster1** [comment]
Sure thing. I'm on Linux Mint 20.1 using zsh but I'll make a new issue.
